import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar/Navbar";
import { AuthContextProvider } from "@/lib/providers/AuthContextProvider";
import { ReactQueryProvider } from "@/lib/providers/ReactQueryProvider";
import { Toaster } from "sonner";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "400"
})

export const metadata: Metadata = {
  title: "TMDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <ReactQueryProvider>
          <AuthContextProvider>
            <Navbar />
            <Toaster position="top-right" richColors />
            {children}               
          </AuthContextProvider>
        </ReactQueryProvider>
        <footer className="bg-black text-white px-6 py-8 text-center">
          <p>Hecho con Next.js 14 por Lucas Llusco.</p>
        </footer>
      </body>
    </html>
  );
}